{
 "title": "De la lonja a la mesa",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "product", "label": "Producto", "query": "datos.lonja.*" }
  ]
 },
 "panels": [
  {
   "title": "PRECIO ACTUAL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    { "target": "datos.lonja.$product" }
   ]
  },
  {
   "title": "PRECIO HISTÓRICO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Precio (€)" }
   ],
   "targets": [
    {
     "target": "aliasByNode(datos.lonja.$product, 2)"
    }
   ]
  },
  {
   "title": "PROMEDIO",
   "type": "table",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 8 },
   "targets": [
    { "target": "datos.lonja.*" }
   ]
  }
 ]
}